# Sources and tests
sonar.sources=apps,libs
sonar.tests=apps,libs

# Test files
sonar.test.inclusions=\
  **/*.spec.ts,\
  **/*.test.ts,\
  **/*.test-setup.ts

# Files excluded from analysis
sonar.exclusions=\
  **/*.woff,\
  **/*.woff2,\
  **/*.ttf,\
  **/*.otf,\
  **/*.png,\
  **/*.jpg,\
  **/*.jpeg,\
  **/*.gif,\
  **/*.ico,\
  **/*.svg,\
  **/*.mts,\

# Files excluded from coverage
sonar.coverage.exclusions=\
  **/*.js,\
  **/main.ts,\
  **/*environment*.ts,\
  **/*.scss,\
  **/*.css,\
  **/*.json,\
  **/*-e2e/**,\
  **/*test-setup.ts,\
  **/*.config.ts,\
  **/*.routes.ts,\
  **/*.model.ts,\
  **/*.php,\
  libs/shared/testing/**,\
  libs/shared/shared-node-test/**

# Vitest coverage reports
sonar.javascript.lcov.reportPaths=**/test-result/**/lcov.info
